### ISSUE TITLE
Nats

### ISSUE THREAD

**Issue by gedw99** [JeffDeCola/my-go-examples#547]
Saw https://github.com/JeffDeCola/my-go-examples/blob/165210c9e0cc670dda77b088f14479eb375ea66c/inter-process-communication-ipc/message-passing/network/asynchronous/pub-sub-nats-network/pub-sub-nats-network.go but it’s empty 

I am adding protobuf based types and wanted to extend to use nats so would be cool if this example was there as a basis

**Comment by JeffDeCola** [comment]
I'll add this back in about a week or so. I'm in the process of revamping this repo.
